### ISSUE TITLE
Eureka与ConfigServer端口设置问题

### ISSUE THREAD

**Issue by addozhang** [ctripcorp/apollo#1032]
按照设计的理解, configserver和eureka使用同一个端口. configserver使用server.port设置端口, 但是eureka client的配置里是把端口hardcode为8080了, 而不是server.port的value. 

```yml
#bootstrap.yml

eureka:
  instance:
    hostname: ${hostname:localhost}
    preferIpAddress: true
  server:
    peerEurekaNodesUpdateIntervalMs: 60000
    enableSelfPreservation: false
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka/
    healthcheck:
      enabled: true
    eurekaServiceUrlPollIntervalSeconds: 60

endpoints:
  health:
    sensitive: false

management:
  security:
    enabled: false
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP
```
