### ISSUE TITLE
docker-compose通过环境变量指定APOLLO_META地址对apollo-portal后台无效(v1.0.0版本)

### ISSUE THREAD

**Issue by zengqinglei** [ctripcorp/apollo#1376]
* 版本：v1.0.0版本
* 服务：apollo-portal
* 说明：
    1. 通过 docker-compose 中环境变量指定**ENV=pro，eureka中显示的环境仍然为test** ！
    2. 通过 docker-compose 中环境变量指定**APOLLO_META地址无效**！
* 其中第2点异常信息：
```
    Get admin server address from meta server failed. env: PRO, meta server address:http://fill-in-pro-meta-server:8080
```

*docker-compose.yml 部分 内容如下：*
```
services:
  apollo-portal:
    container_name: apollo-portal
    build: apollo-portal/src/main/docker/
    image: apollo-portal:1.0.0
    network_mode: host
    expose:
      - "8070"
    restart: always
    volumes:
      - "/opt/logs/100003173:/opt/logs/100003173"
    environment:
      - ENV=pro
      - APOLLO_META=http://192.168.0.103:8080
      - spring_datasource_url=jdbc:mysql://192.168.0.105:3306/ApolloPortalDB?characterEncoding=utf8
      - spring_datasource_username=root
      - spring_datasource_password=123456
```
其他服务configservice，adminservice正常！

大约什么时候能修复这个bug呢？

**Comment by nobodyiam** [comment]
这个不是bug，因为APOLLO_META是给apollo-client用的，不是给apollo-portal用的。

apollo-portal由于需要管理多个环境，所以仍然是以`-Denv=pro -Dpro_meta=xxx`来传入配置。

另外，eureka中显示的test和ENV无关的，不需要care它。如果实在不喜欢看到test的话，可以通过`-Deureka.environment=xxx`来覆盖，具体参考[Configuring Eureka](https://github.com/Netflix/eureka/wiki/Configuring-Eureka#configuration-1)

**Comment by zengqinglei** [comment]
@nobodyiam 那-Denv=pro -Dpro_meta=xxx可以在docker-compose中配置么？如果可以又是怎么配置呢？
非常感谢能给出答案，谢谢！

**Comment by nobodyiam** [comment]
`-Denv=pro -Dpro_meta=xxx`这类是java的system property，可以通过JAVA_OPTS做配置，如：

```yaml
services:
  apollo-portal:
    environment:
      - JAVA_OPTS: "-Denv=pro -Dpro_meta=xxx"
```

config-service和admin-service不需要ENV和APOLLO_META的配置的。

**Comment by zengqinglei** [comment]
@nobodyiam 
根据您所说的，我更改配置如下：
```
version: "3.4"
  
services:
  apollo-portal:
    container_name: apollo-portal
    image: registry.cn-shenzhen.aliyuncs.com/zengql-study/apollo-portal:1.0.0
    network_mode: host
    expose:
      - "8070"
    restart: always
    volumes:
      - "/opt/logs/100003173:/opt/logs/100003173"
    environment:
      - JAVA_OPTS:"-Dpro_meta=http://pro.meta-server.zengql.local"
      - spring_datasource_url=jdbc:mysql://192.168.0.105:3306/ApolloPortalDB?characterEncoding=utf8
      - spring_datasource_username=root
      - spring_datasource_password=123456
```
**docker-compose up -d 启动后，通过日志查看仍然没有得到pro_meta的地址，这是什么原因呢？**
* 日志简要内容：
```
Env health check failed, maybe because of meta server down or configure wrong meta server address. env: PRO, meta server address: http://fill-in-pro-meta-server:8080
```

_注: 我是用v1.0.0源码编译出来的镜像，并未做任何改动！_

**Comment by nobodyiam** [comment]
@zengqinglei 

你最终是使用startup.sh启动的吗？如果是的话，里面的第15行会把操作系统变量JAVA_OPTS拼接进去的

https://github.com/ctripcorp/apollo/blob/master/apollo-portal/src/main/scripts/startup.sh#L15

![image](https://user-images.githubusercontent.com/837658/44299902-ab26bb00-a330-11e8-9f3a-de318060ddbc.png)

**Comment by zengqinglei** [comment]
@nobodyiam 嗯，查看了dockerfile文件
![image](https://user-images.githubusercontent.com/7374317/44300167-238f7b00-a335-11e8-960c-52ed78199e82.png)
我是切换到tag：v1.0.0,源码没有做过任何调整，直接通过docker-compose编排文件如下：
```
version: "3.4"

services:
  apollo-portal:
    container_name: apollo-portal
    build: apollo-portal/src/main/docker/
    image: apollo-portal:1.0.0
    network_mode: host
    expose:
      - "8070"
    restart: always
    depends_on:
      - apollo-adminservice
    volumes:
      - "/opt/logs/100003173:/opt/logs/100003173"
    environment:
      - JAVA_OPTS:"-Dpro_meta=http://pro.meta-server.zengql.local"
      - spring_datasource_url=jdbc:mysql://192.168.0.105:3306/ApolloPortalDB?characterEncoding=utf8
      - spring_datasource_username=root
      - spring_datasource_password=123456
```
麻烦您了，，帮忙看看有什么问题么？
