### ISSUE TITLE
如何打开Apollo 的日志

### ISSUE THREAD

**Issue by alvinwangs** [ctripcorp/apollo#1843]
部署到线上的时候没办法确定链接到config service 失败的原因。没有打印任何日志可供排查。请问如何将apollo 的日志选项打开

**Comment by kezhenxu94** [comment]
在 `application.yml` 中指定 apollo 的日志级别:
```yml
logging:
  level:
    com.ctrip.framework.apollo: debug
```
如果是使用 `application.properties`:
```properties
logging.level.com.ctrip.framework.apollo=debug
```
如果是使用 log4j 或 logback,, 在 `<loggers>` 节点中添加:
```xml
    <logger name="com.ctrip.framework.apollo" additivity="false" level="DEBUG">
    </logger>
```

具体日志级别可以根据实际情况改 `info`, `warn`, `error` 等
