### ISSUE TITLE
springcloud 动态调整Logging Level时，项目私有namespace中的配置 更新无效

### ISSUE THREAD

**Issue by mstao** [ctripcorp/apollo#1911]
现在有一个配置项`logging.level.root`，代表日志级别，如果该项配置在application 的namespace下，实时刷新日志即可有效，但将该配置项移到新建的logger的namespace中，更改该项配置，项目不会刷新改配置. 示例代码：[地址](https://github.com/mstao/apollo-test)

我在项目的application.yml添加如下配置：

```
apollo:
  meta: http://localhost:8762
  bootstrap:
    enabled: true
    namespaces: application,logger
    eagerLoad:
      enabled: true
```

同时在apollo配置页面上配置如下：

![snipaste_2019-01-24_12-53-27](https://user-images.githubusercontent.com/23411433/51655365-5110dc80-1fd7-11e9-8066-c77bd87588ec.png)
