### ISSUE TITLE
按照本项目中k8s部署方法无法成功启动statefulset

### ISSUE THREAD

**Issue by yipingw** [ctripcorp/apollo#2108]
操作系统：centos 7
k8s版本：1.13
结构：一主一从，apollo相关服务都部署在从服务器
问题：按照scripts文件夹中的步骤部署应用，卡在apollo-config-server.yaml文件的创建statefulset这一步，当有状态副本集创建好后，容器启动起来了，但是探针一直无法连通8080端口，报Readiness probe failed: dial tcp 10.244.1.123:8080: connect: connection refused
Back-off restarting failed container
请参见截图：
![image](https://user-images.githubusercontent.com/2724357/55396618-e3ed6a80-5576-11e9-8493-a76a757a0d66.png)

该问题已经困扰我一天了，一直没头绪，配置文件请参看附件，谢谢。

service-mysql-for-apollo-dev-env.yaml

```
---
# 为外部 mysql 服务设置 service
kind: Service
apiVersion: v1
metadata:
  namespace: sre
  name: service-mysql-for-apollo-dev-env
  labels:
    app: service-mysql-for-apollo-dev-env
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
  sessionAffinity: None

---
kind: Endpoints
apiVersion: v1
metadata:
  namespace: sre
  name: service-mysql-for-apollo-dev-env
subsets:
  - addresses:
      - ip: 10.104.232.16 #这里的IP是否是填写mysql获取的集群IP？
    ports:
      - protocol: TCP
        port: 3306

```

service-apollo-config-server-dev.yaml

```
---
# configmap for apollo-config-server-dev
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: sre
  name: configmap-apollo-config-server-dev
data:
  application-github.properties: |
    spring.datasource.url = jdbc:mysql://service-mysql-for-apollo-dev-env.sre:3306/DevApolloConfigDB?characterEncoding=utf8
    spring.datasource.username = root
    spring.datasource.password = jc@mysql
    eureka.service.url = http://statefulset-apollo-config-server-dev-0.service-apollo-meta-server-dev:8080/eureka/,http://statefulset-apollo-config-server-dev-1.service-apollo-meta-server-dev:8080/eureka/,http://statefulset-apollo-config-server-dev-2.service-apollo-meta-server-dev:8080/eureka/

---
kind: Service
apiVersion: v1
metadata:
  namespace: sre
  name: service-apollo-meta-server-dev
  labels:
    app: service-apollo-meta-server-dev
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: pod-apollo-config-server-dev
  type: ClusterIP
  clusterIP: None
  sessionAffinity: ClientIP

---
kind: Service
apiVersion: v1
metadata:
  namespace: sre
  name: service-apollo-config-server-dev
  labels:
    app: service-apollo-config-server-dev
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002
  selector:
    app: pod-apollo-config-server-dev 
  type: NodePort
  sessionAffinity: ClientIP

---
kind: StatefulSet
apiVersion: apps/v1beta2
metadata:
  namespace: sre
  name: statefulset-apollo-config-server-dev
  labels:
    app: statefulset-apollo-config-server-dev
spec:
  serviceName: service-apollo-meta-server-dev
  replicas: 3
  selector:
    matchLabels:
      app: pod-apollo-config-server-dev
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pod-apollo-config-server-dev
    spec:
      nodeSelector:
        kubernetes.io/hostname: "k8s-worker-01"

      volumes:
        - name: volume-configmap-apollo-config-server-dev
          configMap:
            name: configmap-apollo-config-server-dev
            items:
              - key: application-github.properties
                path: application-github.properties
      
      containers:
        - image: 10.10.10.135:5000/apollo-config-server:v1.3.0
          securityContext:
            privileged: true
          imagePullPolicy: Always
          name: container-apollo-config-server-dev
          ports:
            - protocol: TCP
              containerPort: 8080
          
          volumeMounts:
            - name: volume-configmap-apollo-config-server-dev
              mountPath: /apollo-config-server/config/application-github.properties
              subPath: application-github.properties
          
          env:
            - name: APOLLO_CONFIG_SERVICE_NAME
              value: "service-apollo-config-server-dev.sre"
          
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds:  120
            periodSeconds: 10

      imagePullSecrets:
        - name: sre-registry-secret
          
      dnsPolicy: ClusterFirst
      restartPolicy: Always
```
