### ISSUE TITLE
项目配置了apollo不起作用

### ISSUE THREAD

**Issue by zhaoyunxing92** [ctripcorp/apollo#2215]
我用1.4.0的版本,但是yml文件不起用,文件已经拉倒本地了

yml配置
```yaml
app:
  id: spring-boot-apollo
apollo:
  meta: http://127.0.0.1:8080
  cacheDir: ./apolloconfig 
  bootstrap:
    enabled: true
    namespaces: application.yml
    eagerLoad:
      enabled: true
```
拉取的配置信息
![cache](https://gitee.com/sunny9/resource/raw/master/img/apollo-cache.png)

**Comment by nobodyiam** [comment]
需要确保本地没有填写server.port属性

**Comment by zhaoyunxing92** [comment]
我本地只设置了apollo的配置,其他都在apollo上配置的

**Comment by nobodyiam** [comment]
可以参考一下[spring-cloud-zuul](https://github.com/ctripcorp/apollo-use-cases/tree/master/spring-cloud-zuul)

**Comment by zhaoyunxing92** [comment]
现在问题是application.yml不行,只能用application.properties

**Comment by nobodyiam** [comment]
我使用[spring-cloud-zuul](https://github.com/ctripcorp/apollo-use-cases/tree/master/spring-cloud-zuul)测试了是没问题的

1. 在apollo创建application.yml
如`http://106.12.25.204:8070/config.html?#/appid=spring-cloud-zuul`

```yml
server:
  port: 9090
zuul:
  routes:
    test:
      path: /**
      url: https://github.com
```

2. 修改[Application.java](https://github.com/ctripcorp/apollo-use-cases/blob/master/spring-cloud-zuul/src/main/java/com/ctrip/framework/apollo/use/cases/spring/cloud/zuul/Application.java)，注入`application.yml`配置

```java
@EnableApolloConfig("application.yml")
```

3. 修改[ZuulPropertiesRefresher.java](https://github.com/ctripcorp/apollo-use-cases/blob/master/spring-cloud-zuul/src/main/java/com/ctrip/framework/apollo/use/cases/spring/cloud/zuul/ZuulPropertiesRefresher.java)监听`application.yml`的变化

这步非必须，只是为了能监听配置变化，重新刷新zuul的路由

```
  @ApolloConfigChangeListener(interestedKeyPrefixes = "zuul.", value = "application.yml")
  public void onChange(ConfigChangeEvent changeEvent) {
    refreshZuulProperties(changeEvent);
  }
```

4. 配置[application.properties](https://github.com/ctripcorp/apollo-use-cases/blob/master/spring-cloud-zuul/src/main/resources/application.properties)中的`apollo.meta`地址

5. 启动程序

程序会以前面配置的端口启动

**Comment by nobodyiam** [comment]
我使用[spring-cloud-zuul](https://github.com/ctripcorp/apollo-use-cases/tree/master/spring-cloud-zuul)测试了是没问题的

1. 在apollo创建application.yml
如`http://106.12.25.204:8070/config.html?#/appid=spring-cloud-zuul`

```yml
server:
  port: 9090
zuul:
  routes:
    test:
      path: /**
      url: https://github.com
```

2. 修改[Application.java](https://github.com/ctripcorp/apollo-use-cases/blob/master/spring-cloud-zuul/src/main/java/com/ctrip/framework/apollo/use/cases/spring/cloud/zuul/Application.java)，注入`application.yml`配置

```java
@EnableApolloConfig("application.yml")
```

3. 修改[ZuulPropertiesRefresher.java](https://github.com/ctripcorp/apollo-use-cases/blob/master/spring-cloud-zuul/src/main/java/com/ctrip/framework/apollo/use/cases/spring/cloud/zuul/ZuulPropertiesRefresher.java)监听`application.yml`的变化

这步非必须，只是为了能监听配置变化，重新刷新zuul的路由

```
  @ApolloConfigChangeListener(interestedKeyPrefixes = "zuul.", value = "application.yml")
  public void onChange(ConfigChangeEvent changeEvent) {
    refreshZuulProperties(changeEvent);
  }
```

4. 配置[application.properties](https://github.com/ctripcorp/apollo-use-cases/blob/master/spring-cloud-zuul/src/main/resources/application.properties)中的`apollo.meta`地址

5. 启动程序

程序会以前面配置的端口启动
