### ISSUE TITLE
feign使用时获取不到变量

### ISSUE THREAD

**Issue by zhangfb95** [ctripcorp/apollo#2270]
在spring boot和apollo做集成的时候，feign的配置获取不到。如下例子，发现变量biz.baidu-ai.url并没有被替换。如果去掉namespaces，那么就能被替换。不去掉namespaces，就不能被替换。请问这是为什么呢？有什么解决办法吗？

涉及版本：
1. spring-boot // 2.0.4.RELEASE
2. apollo-client // 1.3.0
3. spring-cloud // Finchley.SR1

```yml
app:
  id: xxx

# apollo-configservice地址
apollo:
  meta: xxx
  bootstrap:
    enabled: true
    namespaces: xxx
    eagerLoad:
      enabled: true
```

```java
@FeignClient(name = "bai", url = "${biz.baidu-ai.url}")
public interface BaiFeign {
}
```

```java
@GetMapping("hello")
public Response<Void> hello() {
    baiFeign.getToken("aa", "bb", "cc");
    return ResponseGenerator.success();
}
```
