### ISSUE TITLE
拉取默认配置问题

### ISSUE THREAD

**Issue by genghaizhou** [ctripcorp/apollo#2318]
```
apollo:
  bootstrap:
    enabled: true
    namespaces: application.yml
```
默认依然会拉取 application.properties
但是我发布application.properties，导致启动时报警告
`Cause: [status code: 404] Could not find config for namespace - appId: housing102, cluster: default, namespace: application, please check whether the configs are released in Apollo!
`
为什么我已经指定了配置 还会拉取 application.properties?
