### ISSUE TITLE
如何在yml文件中读取其它namespace的配置

### ISSUE THREAD

**Issue by Farwell-Liu** [ctripcorp/apollo#2455]
在yml文件中我当前的namespace是SpaceA
```
apollo:
  bootstrap:
    enabled: true #指定启用apollo
    namespaces: SpaceA #指定namespace

```
但是我想读取其它namespace的配置到yml文件中
```
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SpaceB.spring.datasource.url}
    username: ${SpaceB.spring.datasource.username}
    password: ${SpaceB.spring.datasource.password}
```
但是很显然这种写法是不对的, 因为客户端哪一段是namespace,哪一段是key, 有没有什么办法呢? 谢谢!

**Comment by nobodyiam** [comment]
```yml
apollo:
  bootstrap:
    enabled: true #指定启用apollo
    namespaces: SpaceA, SpaceB #指定namespace
```

```yml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${datasource-key-in-space-b}
    username: ${username-key-in-space-b}
    password: ${password-key-in-space-b}
```
