### ISSUE TITLE
接入LDAP使用group后，获取的用户信息永远是组中的第一个用户的信息

### ISSUE THREAD

**Issue by raoxiaoyan** [ctripcorp/apollo#2897]
apollo的版本为：1.5.0
以下接入及调试信息：
ldap的接入mapping和group配置：
```
ldap:
  mapping:
    objectClass: "inetOrgPerson"
    loginId: "uid"
    rdnKey: "uid"
    userDisplayName: "displayName"
    email: "mail"
  group:
    objectClass: "posixGroup"
    groupBase: ""
    groupSearch: "(&(cn=apollo_admins))"
    groupMembership: "memberUid"
```
调用LdapUserService的方法findByUserId，返回如下结果：
![image](https://raoxiaoyan.github.io/img/img1.png)
而代码又只简单获取第一个用户对象直接返回：
![image](https://user-images.githubusercontent.com/22835296/71969766-4d0ab880-3242-11ea-9854-4d9486b24071.png)
