### ISSUE TITLE
k8s 部署 apollo，对接 ldap 无效

### ISSUE THREAD

**Issue by Xindahuang** [ctripcorp/apollo#3073]
**Describe the bug**
将 application-ldap.yaml & startup.sh 以 configmap 形式挂载进去后，依旧使用的是自带的认真方式，ldap 未生效

**To Reproduce**
配置：
```yml
spring:
  ldap:
    base: "dc=xxx,dc=xxx"
    username: "cn=admin,dc=xxx,dc=xxx" # 配置管理员账号，用于搜索、匹配用户
    password: "admin"
    searchFilter: "(uid={0})"  # 用户过滤器，登录的时候用这个过滤器来搜索用户
    urls:
    - "ldap://xxx.com:389"

ldap:
  mapping: # 配置 ldap 属性
    objectClass: "inetOrgPerson" # ldap 用户 objectClass 配置
    loginId: "cn" # ldap 用户惟一 id，用来作为登录的 id
    rdnKey: "uid" # ldap rdn key
    userDisplayName: "cn" # ldap 用户名，用来作为显示名
    email: "mail" # ldap 邮箱属性
  group: # 启用group search，启用后只有特定group的用户可以登录apollo
    objectClass: "organizationalUnit"  # 配置groupClassName
    groupBase: "ou=groups" # group search base
    groupSearch: "(&(cn=users))" # group filter
    groupMembership: "memberUid" # group memberShip eg. member or memberUid
```
**Expected behavior**
通过 ldap 认证
