### ISSUE TITLE
关于python flask接入apollo的问题

### ISSUE THREAD

**Issue by qxqxq** [ctripcorp/apollo#3251]
apollo支持map嵌套或者数组嵌套吗？如何实现？谢谢
类似yaml配置文件
 
database config {'DATABASE': {'DEFAULT': {...}}}
```
DATABASE:
    DEFAULT:
        USER: root
        PASSWORD: test
        HOST: 127.0.0.1
        PORT: 3306
        DATABASE: test
    MASTER:
        USER: root
        PASSWORD: test
        HOST: 127.0.0.1
        PORT: 3306
        DATABASE: test
```
{"LOG_HANDLERS": [{"name": "system_log", ...}, ...]}
```
LOG_HANDLERS: 
        - name: system_log
          file: 'system_{time:YYYY-MM-DD}.log'
          
          filter: system
          options:
            retention: '30 days'
            format: '{time:YYYY-MM-DD HH:mm:ss}|{message}'

        - name: operate_log
          file: 'operate_{time:YYYY-MM-DD}.log'
          filter: operate
          options:
            retention: '30 days'
            format: '{message}'
```
