### ISSUE TITLE
用docker quick start mysql 有密码怎么办？ 

### ISSUE THREAD

**Issue by elisayys** [ctripcorp/apollo#3265]
用docker quick start mysql 有密码怎么办？ 本地的mysql root 有密码 ，请问  docker-compose.yml  这个文件要怎么修改呢？

**Comment by nobodyiam** [comment]
可以试试传入操作系统环境变量：SPRING_DATASOURCE_URL、SPRING_DATASOURCE_USERNAME、SPRING_DATASOURCE_PASSWORD

**Comment by tonycody** [comment]
`version: '2'
  
services:
  apollo-quick-start:
    image: nobodyiam/apollo-quick-start
    container_name: apollo-quick-start
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://127.0.0.1:3306/ApolloConfigDB?characterEncoding=utf8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=ly2020
    ports:
      - "8080:8080"
      - "8070:8070"`

用一个已存在的mysql容器，启不来~

**Comment by tonycody** [comment]
> 可以试试传入操作系统环境变量：SPRING_DATASOURCE_URL、SPRING_DATASOURCE_USERNAME、SPRING_DATASOURCE_PASSWORD

看过源码了，不行的~

demo.sh 里面是写死的~

**Comment by nobodyiam** [comment]
可以试一下用`SPRING_APPLICATION_JSON`这个操作系统环境变量

```yaml
version: '2'
  
services:
  apollo-quick-start:
    image: nobodyiam/apollo-quick-start
    container_name: apollo-quick-start
    environment:
      - SPRING_APPLICATION_JSON={"spring":{"datasource":{"url":"jdbc:mysql://127.0.0.1:3306/ApolloConfigDB?characterEncoding=utf8","username":"root","password":"ly2020"}}}
    ports:
      - "8080:8080"
      - "8070:8070"
```

**Comment by tonycody** [comment]
@nobodyiam 不行的，因为那个demo.sh里面是2个配置，我优化了一下。自己用你们那个Dockerfile重新打了个本地镜像，可以用了。

https://github.com/nobodyiam/apollo-build-scripts/blob/master/demo.sh

这个脚本要调整一下~因为docker apollo-quick-start镜像用的是这个shell脚本执行的~~~

环境变量要这个脚本可以认才行。

我改成了这样~~~

> demo.sh
```shell
# apollo config db info
apollo_config_db_url=$APOLLO_CONFIG_DB_URL
apollo_config_db_username=$APOLLO_DB_USERNAME
apollo_config_db_password=$APOLLO_DB_PASSWORD
apollo_portal_db_url=$APOLLO_PORTAL_DB_URL
apollo_portal_db_username=$APOLLO_DB_USERNAME
apollo_portal_db_password=$APOLLO_DB_PASSWORD

if [[ -z "$apollo_config_db_url" ]]; then
    apollo_config_db_url=jdbc:mysql://localhost:3306/ApolloConfigDB?characterEncoding=utf8
fi

# apollo portal db info
if [[ -z "$apollo_portal_db_url" ]]; then
    apollo_portal_db_url=jdbc:mysql://localhost:3306/ApolloPortalDB?characterEncoding=utf8
fi

if [[ -z "$apollo_config_db_username" ]]; then
    apollo_config_db_username=root
    apollo_portal_db_username=root
fi

if [[ -z "$apollo_config_db_password" ]]; then
    apollo_config_db_password=
    apollo_portal_db_password=
fi
```

> apollo-quick-start.yml
```yml
version: '2'
  
services:
  apollo-quick-start:
    image: f8475a8f6183
    container_name: apollo-quick-start
    environment:
      - APOLLO_CONFIG_DB_URL=jdbc:mysql://192.168.100.40:3306/ApolloConfigDB?characterEncoding=utf8
      - APOLLO_PORTAL_DB_URL=jdbc:mysql://192.168.100.40:3306/ApolloPortalDB?characterEncoding=utf8
      - APOLLO_DB_USERNAME=root
      - APOLLO_DB_PASSWORD=ly2020
    ports:
      - "8080:8080"
      - "8070:8070"
```
使用已存在的Docker镜像不影响，不使用已存在的Docker镜像还是按之前的方式来走就行了~

改动，PR一下？

![image](https://user-images.githubusercontent.com/6773121/95679855-17975f00-0c08-11eb-96fb-0a22423939d2.png)
