### ISSUE TITLE
接入 LDAP 的 groupSearch 要匹配多个组名，该怎么写？

### ISSUE THREAD

**Issue by dmanbu** [ctripcorp/apollo#3605]
portal 版本：1.6.2

配置：
```
spring:
  ldap:
    base: "dc=test,dc=com"
    username: "cn=connect-apollo,ou=Service,dc=test,dc=com"
    password: "password"
    searchFilter: "(uid={0})"
    urls:
    - "ldap://10.240.1.10:389"

ldap:
  mapping:
    objectClass: "inetOrgPerson"
    loginId: "uid"
    rdnKey: "cn"
    userDisplayName: "displayName"
    email: "mail"
  group:
    objectClass: "groupOfMembers"
    groupBase: "ou=Groups"
    groupSearch: "(|(cn=manager)(cn=sa)(cn=backdev))"
    groupMembership: "member"
```

我在注释掉 groupSearch 时，是可以登录的，但加上 groupSearch 就不能登录了，查看了一下日志，没有任何报错
是否是我的 groupSearch 配置有问题？
