### ISSUE TITLE
configservice增加security控制不生效

### ISSUE THREAD

**Issue by leohsu91** [ctripcorp/apollo#918]
你好，我在configservice增加了spring security的支持。
修改如下：
引入了
```
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-security</artifactId>
</dependency>
```

修改了application.yml
增加了
```
security:
  user:
    password: admin
    name: admin
  basic:
    enabled: true
```
修改client注册地址：
```
client:
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:8080/eureka/
```

但是启动项目后并不生效，不输入账号密码依然能够进去注册中心的控制台。何解？
